name: wordpress_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  collection: ^1.18.0
  crypto: ^3.0.5
  dio: ^5.6.0
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^6.0.0
  html: ^0.15.4
  intl: ^0.19.0
  page_transition: ^2.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: iranSans
      fonts:
        - asset: assets/fonts/Iranian-Sans.ttf

    - family: Samim
      fonts:
        - asset: assets/fonts/Samim.ttf
        - asset: assets/fonts/Samim-Bold.ttf
        - asset: assets/fonts/Samim-FD.ttf

    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf

    - family: nanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf